name: pkg

on:
  workflow_dispatch:

jobs:
  pkg-build:
    runs-on: windows-2019
    name: Build pkg
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install conan
      run: |
        python -m pip install conan

    - name: Find conan for MSYS2
      shell: bash
      run: |
        echo "CONAN_PATH=$(dirname $(which conan))" > msys2rc

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        release: false

    - name: Build
      shell: msys2 {0}
      run: |
        . msys2rc
        export PATH="$CONAN_PATH:$PATH"
        conan profile detect
        conan build -c tools.microsoft.bash:subsystem=msys2 -c "tools.microsoft.bash:path=C:\msys64\usr\bin\bash.exe" .
